# kafka-ui-values.yaml
replicaCount: 1

image:
  registry: docker.io
  repository: provectuslabs/kafka-ui
  tag: v0.7.2
  pullPolicy: IfNotPresent

env:
  - name: KAFKA_CLUSTERS_0_NAME
    value: "dt-redpanda-cluster"
  - name: KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS
    value: "dt-redpanda-0.dt-redpanda.dt.svc.cluster.local:9093,dt-redpanda-1.dt-redpanda.dt.svc.cluster.local:9093,dt-redpanda-2.dt-redpanda.dt.svc.cluster.local:9093"
  - name: KAFKA_CLUSTERS_0_KAFKACONNECT_0_NAME
    value: "kafka-connect"
  - name: KAFKA_CLUSTERS_0_KAFKACONNECT_0_ADDRESS
    value: "http://kafka-connect.dt.svc.cluster.local:8083"
  - name: KAFKA_CLUSTERS_0_PROPERTIES_SECURITY_PROTOCOL
    value: "SASL_PLAINTEXT"
  - name: KAFKA_CLUSTERS_0_PROPERTIES_SASL_MECHANISM
    value: "SCRAM-SHA-512"
  - name: KAFKA_CLUSTERS_0_PROPERTIES_SASL_JAAS_CONFIG
    value: "org.apache.kafka.common.security.scram.ScramLoginModule required username=\"superuser\" password=\"pw123!\";"

# auth:
#   enabled: true
#   sasl:
#     enabled: true
#     protocol: "SASL_PLAINTEXT"
#     mechanism: "SCRAM-SHA-512"
#     sername: "superuser"
#     password: "pw123!"


service:
  type: ClusterIP
  port: 8080

ingress:
  enabled: false
  # Enable and configure if you want external access
  # className: "nginx"
  # annotations: {}
  # hosts:
  #   - host: kafka-ui.your-domain.com
  #     paths:
  #       - path: /
  #         pathType: Prefix
  # tls: []

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 100m
    memory: 256Mi

nodeSelector: {}

tolerations: []

affinity: {}