{{- if .Values.auth.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "kafka-connect.fullname" . }}-auth
  labels:
    {{- include "kafka-connect.labels" . | nindent 4 }}
  {{- with .Values.commonAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
type: Opaque
data:
  {{- if .Values.auth.sasl.enabled }}
  sasl-username: {{ .Values.auth.sasl.username | b64enc | quote }}
  sasl-password: {{ .Values.auth.sasl.password | b64enc | quote }}
  sasl-jaas-config: {{ printf "org.apache.kafka.common.security.scram.ScramLoginModule required username=\"%s\" password=\"%s\";" .Values.auth.sasl.username .Values.auth.sasl.password | b64enc | quote }}
  {{- end }}
{{- end }} 